# Generated by Django 2.2.16 on 2020-09-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('number_accident', models.CharField(max_length=20, unique=True, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.DateField(verbose_name='Время')),
                ('type_accident', models.CharField(max_length=50, verbose_name='Вид ДТП')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('street', models.CharField(blank=True, max_length=50, verbose_name='Улица')),
                ('home', models.CharField(blank=True, max_length=20, verbose_name='Дом')),
                ('road', models.CharField(blank=True, max_length=100, verbose_name='Дорога')),
                ('kilometer', models.CharField(blank=True, max_length=10, verbose_name='Километр')),
                ('metre', models.CharField(blank=True, max_length=5, verbose_name='Метр')),
                ('latitude_degrees', models.CharField(max_length=4, verbose_name='Широта, градусы')),
                ('latitude_minutes', models.CharField(max_length=4, verbose_name='Широта, минуты')),
                ('latitude_seconds', models.CharField(max_length=4, verbose_name='Широта, секунды')),
                ('longitude_degrees', models.CharField(max_length=4, verbose_name='Долгота, градусы')),
                ('longitude_minutes', models.CharField(max_length=4, verbose_name='Долгота, минуты')),
                ('longitude_seconds', models.CharField(max_length=4, verbose_name='Долгота, секунды')),
                ('lost', models.IntegerField(default=0, verbose_name='Погибло')),
                ('lost_children', models.IntegerField(default=0, verbose_name='Погибло детей')),
                ('wounded', models.IntegerField(default=0, verbose_name='Ранено')),
                ('wounded_children', models.IntegerField(default=0, verbose_name='Ранено детей')),
                ('division_reg_accident', models.CharField(max_length=100, verbose_name='Подразделение, оформившее ДТП')),
                ('ndu', models.CharField(max_length=100, verbose_name='НДУ')),
                ('ndu_1', models.CharField(blank=True, max_length=100, verbose_name='НДУ.1')),
                ('ndu_2', models.CharField(blank=True, max_length=100, verbose_name='НДУ.2')),
                ('ndu_3', models.CharField(blank=True, max_length=100, verbose_name='НДУ.3')),
                ('uds_objects_in_place', models.CharField(max_length=100, verbose_name='Объекты УДС на месте')),
                ('uds_objects_in_place_1', models.CharField(blank=True, max_length=100, verbose_name='Объекты УДС на месте.1')),
                ('uds_objects_nearby', models.CharField(max_length=100, verbose_name='Объекты УДС вблизи')),
                ('uds_objects_nearby_1', models.CharField(blank=True, max_length=100, verbose_name='Объекты УДС вблизи.1')),
                ('uds_objects_nearby_2', models.CharField(blank=True, max_length=100, verbose_name='Объекты УДС вблизи.2')),
                ('uds_objects_nearby_3', models.CharField(blank=True, max_length=100, verbose_name='Объекты УДС вблизи.3')),
                ('factors_of_driving_mode', models.CharField(max_length=200, verbose_name='Факторы, влияющие на режим движения')),
                ('factors_of_driving_mode_1', models.CharField(blank=True, max_length=200, verbose_name='Факторы, влияющие на режим движения.1')),
                ('factors_of_driving_mode_2', models.CharField(blank=True, max_length=200, verbose_name='Факторы, влияющие на режим движения.2')),
                ('factors_of_driving_mode_3', models.CharField(blank=True, max_length=200, verbose_name='Факторы, влияющие на режим движения.3')),
                ('condition_of_carriageway', models.CharField(max_length=100, verbose_name='Состояние проезжей части')),
                ('weather_condition', models.CharField(max_length=100, verbose_name='Состояние погоды')),
                ('weather_condition_1', models.CharField(blank=True, max_length=100, verbose_name='Состояние погоды.1')),
                ('lighting', models.CharField(max_length=100, verbose_name='Освещение')),
                ('concentration_accidents', models.CharField(max_length=10, verbose_name='Является местом концентрации ДТП')),
                ('road_on_plan', models.CharField(max_length=20, verbose_name='Дорога в плане')),
                ('profile_of_road', models.CharField(max_length=500, verbose_name='Профиль дороги')),
                ('number_of_lanes', models.IntegerField(verbose_name='Количество полос')),
                ('lane_where_accident', models.IntegerField(verbose_name='Полоса, в которой произошло ДТП')),
                ('width_roadway', models.IntegerField(verbose_name='Ширина проезжей части')),
                ('width_shoulder', models.IntegerField(default=0, verbose_name='Ширина обочины')),
                ('width_sidewalk', models.IntegerField(default=0, verbose_name='Ширина тротуара')),
                ('width_dividing_strip', models.IntegerField(default=0, verbose_name='Ширина разделительной полосы')),
                ('type_dividing_strip', models.CharField(max_length=100, verbose_name='Вид разделительной полосы')),
                ('type', models.CharField(max_length=100, verbose_name='Вид покрытия')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота')),
                ('location', models.CharField(default='other', max_length=10, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='Violations_cameras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('id_violations', models.CharField(max_length=15, unique=True, verbose_name='id нарушения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.DateField(verbose_name='Время')),
                ('date_time', models.DateTimeField(verbose_name='Дата, время')),
                ('id_cameras', models.CharField(max_length=25, verbose_name='id камеры')),
                ('model_cameras', models.CharField(max_length=25, verbose_name='Модель камеры')),
                ('type_cameras', models.CharField(max_length=25, verbose_name='Тип камеры')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота')),
                ('article_offenses_in_CODE', models.CharField(max_length=20, verbose_name='Статья правонарушения в КОАП')),
                ('content_article', models.CharField(blank=True, max_length=100, verbose_name='Содержание статьи')),
                ('speed_of_violation', models.IntegerField(verbose_name='Зафиксированная скорость в момент нарушения, км/ч')),
            ],
        ),
    ]
