# Generated by Django 2.2.16 on 2020-09-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collisions', '0002_auto_20200921_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=10, verbose_name='Фамилия')),
            ],
        ),
    ]
