# Generated by Django 2.2.16 on 2020-09-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collisions', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtp',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='time',
            field=models.CharField(max_length=8, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='violations_cameras',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='violations_cameras',
            name='date_time',
            field=models.CharField(max_length=20, verbose_name='Дата, время'),
        ),
        migrations.AlterField(
            model_name='violations_cameras',
            name='time',
            field=models.CharField(max_length=8, verbose_name='Время'),
        ),
    ]
