# Generated by Django 2.2.16 on 2020-09-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collisions', '0004_auto_20200921_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtp',
            name='lane_where_accident',
            field=models.CharField(blank=True, max_length=10, verbose_name='Полоса, в которой произошло ДТП'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='lost',
            field=models.CharField(blank=True, max_length=10, verbose_name='Погибло'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='lost_children',
            field=models.CharField(blank=True, max_length=10, verbose_name='Погибло детей'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='number_of_lanes',
            field=models.CharField(blank=True, max_length=10, verbose_name='Количество полос'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='width_dividing_strip',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ширина разделительной полосы'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='width_roadway',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ширина проезжей части'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='width_shoulder',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ширина обочины'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='width_sidewalk',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ширина тротуара'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='wounded',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ранено'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='wounded_children',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ранено детей'),
        ),
    ]
