# Generated by Django 2.2.16 on 2020-09-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collisions', '0005_auto_20200921_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtp',
            name='number_accident',
            field=models.CharField(max_length=20, verbose_name='Номер'),
        ),
    ]
